---
# tasks file for el-samba-realm
- name: Prep | install required packages
  package:
    name: "{{ required_pkgs }}"
    state: present

- name: Configure | smb.conf
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [global]
       workgroup = {{ ad_server_domain_short }}
       server string = Samba Server Version %v
       hosts allow = 127., {{ ip_allow }}.
       socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072
       use sendfile = true
       min protocol = SMB2
       inherit permissions = yes
       ea support = yes
       vfs objects = fruit streams_xattr
       fruit:metadata = stream
       fruit:model = MacSamba
       fruit:veto_appledouble = no
       fruit:posix_rename = yes
       fruit:zero_file_id = yes
       fruit:wipe_intentionally_left_blank_rfork = yes
       fruit:delete_empty_adfiles = yes
       fruit:nfs_aces = no

       log file = /var/log/samba/log.%m
       max log size = 50
      #log level =3

       security = ads
       realm = {{ ad_server_domain }}
       idmap config * : backend = tdb
       idmap config * : range = 100000-299999
       idmap config {{ ad_server_domain_short|upper }} : backend = rid
       idmap config {{ ad_server_domain_short|upper }} : range = 10000-99999
       winbind separator = +
       winbind enum users = yes
       winbind enum groups = yes
       winbind use default domain = yes
       winbind refresh tickets = yes

       load printers = No
       cups options = raw
       printcap name = /dev/null

- name: Configure | Enable SMB in firewall
  firewalld:
    service: samba
    permanent: true
    state: enabled
  notify: reload firewall